Remove thumbnail toggle small
box/box-content-preview pull request #1449
Opened 2022-06-11 04:03 UTC by ivanthai

This is hidden on smaller modalities in order to prioritize other functions

https://zpl.io/dxDDLEp

![preview-controls-hide-thumbnail-toggle](https://user-images.githubusercontent.com/1041516/173171780-1fc7eba2-16bc-4b7e-b1e9-27036b5ccd50.gif)

2022-06-13 14:47 UTC, jstoffan requested changes
@ivanthai, we have [styling](https://github.com/box/box-content-preview/blob/master/src/lib/viewers/doc/_docBase.scss#L141) that handles responsive behavior for this element today. We'll need to make sure this new code is compatible.

2022-06-17 21:19 UTC, ivanthai commented
Seems like it would make sense to convert the other thumbnail component CSS to the new breakpoints...probably should define that breakpoint number in BUIE

2022-06-21 15:14 UTC, jstoffan commented
@ivanthai, are we planning to unify the breakpoints? I think we'll run into some odd behaviors otherwise.

2022-07-02 01:15 UTC, jstoffan approved these changes

2022-07-02 02:54 UTC, merged